version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "techass"
      POSTGRES_USER: "techass"
      POSTGRES_PASSWORD: "qwerty123"
    ports:
      - "5432:5432"